
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/STARTER-jpa03
owner: ucsb-cs156-s24
repo_name: STARTER-jpa03
pull_requests: [{"author":{"id":"MDQ6VXNlcjQwNzc1MzY0","is_bot":false,"login":"Aasish-Virjala","name":"Aasish Virjala"},"headRefName":"fix-logout","number":9,"title":"fixed logout button","url":"https://github.com/ucsb-cs156-s24/STARTER-jpa03/pull/9"}]
